require('dotenv').config({ path: './apps/api/.env' });
require('dotenv').config({ path: './apps/worker/.env' });

module.exports = {
  apps: [
    {
      name: 'smartrentroll-api',
      script: 'apps/api/server.js',
      interpreter: 'node',
      cwd: './',
      env: {
        NODE_ENV: 'production',
        PORT: process.env.PORT || 3001,
        MONGODB_URI: process.env.MONGODB_URI,
        REDIS_URL: process.env.REDIS_URL,
        JWT_SECRET: process.env.JWT_SECRET,
        JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,
        JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN || '15m',
        JWT_REFRESH_EXPIRES_IN: process.env.JWT_REFRESH_EXPIRES_IN || '7d',
        MPESA_CONSUMER_KEY: process.env.MPESA_CONSUMER_KEY,
        MPESA_CONSUMER_SECRET: process.env.MPESA_CONSUMER_SECRET,
        MPESA_BUSINESS_SHORT_CODE: process.env.MPESA_BUSINESS_SHORT_CODE,
        MPESA_PASSKEY: process.env.MPESA_PASSKEY,
        MPESA_ENVIRONMENT: process.env.MPESA_ENVIRONMENT || 'production',
        CORS_ORIGIN: process.env.CORS_ORIGIN,
        RATE_LIMIT_WINDOW_MS: process.env.RATE_LIMIT_WINDOW_MS || '900000',
        RATE_LIMIT_MAX_REQUESTS: process.env.RATE_LIMIT_MAX_REQUESTS || '100',
      },
      error_file: './logs/api-error.log',
      out_file: './logs/api-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      instances: 1,
      exec_mode: 'fork',
    },
    {
      name: 'smartrentroll-worker',
      script: 'apps/worker/worker.js',
      interpreter: 'node',
      cwd: './',
      env: {
        NODE_ENV: 'production',
        MONGODB_URI: process.env.MONGODB_URI,
        REDIS_URL: process.env.REDIS_URL,
        JWT_SECRET: process.env.JWT_SECRET,
        JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,
        MPESA_CONSUMER_KEY: process.env.MPESA_CONSUMER_KEY,
        MPESA_CONSUMER_SECRET: process.env.MPESA_CONSUMER_SECRET,
        MPESA_BUSINESS_SHORT_CODE: process.env.MPESA_BUSINESS_SHORT_CODE,
        MPESA_PASSKEY: process.env.MPESA_PASSKEY,
        MPESA_ENVIRONMENT: process.env.MPESA_ENVIRONMENT || 'production',
      },
      error_file: './logs/worker-error.log',
      out_file: './logs/worker-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      instances: 1,
      exec_mode: 'fork',
    },
  ],
};
